name: build-hugo-content
on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build-obsidian:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Pip Install Obsidian2Hugo
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            obsidian-to-hugo
          
      - name: Create Hugo content
        run: python -m obsidian_to_hugo --obsidian-vault-dir=doc --hugo-content-dir=hugo
        shell: sh
          
      - name: Count files in hugo folder
        run: ll hugo/ | wc -l
        shell: sh
        
      - name: Push Hugo to Brume-Website
        uses: cpina/github-action-push-to-another-repository@v1.6
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          # Source directory from the origin directory
          source-directory: hugo
          # Name of the destination username/organization
          destination-github-username: portevent
          # Destination repository
          destination-repository-name: Brume-Website
          # Email for the git commit
          user-email: porte@magous.fr
          # [Optional] set target branch name for the destination repository. Defaults to "main"
          target-branch: main # optional, default is main
          # [Optional] commit message for the output repository. ORIGIN_COMMIT is replaced by the URL@commit in the origin repo
          commit-message: Update Doc content
          # [Optional] The directory to wipe and replace in the target repository
          target-directory: content/doc
